---
kind: pipeline
name: default

steps:
  - name: lint
    image: node
    commands:
      - npm install
      - npm run lint
  - name: build
    image: node
    environment:
      GH_TOKEN:
        from_secret: token
    commands:
      - npm install
      - npm run publish
